CREATE TABLE BOOKS_AUD (
  EVENT_ID int(11) NOT NULL AUTO_INCREMENT,
  EVENT_DATE datetime NOT NULL,
  EVENT_TYPE varchar(10) DEFAULT NULL,
  BOOK_ID int(11) NOT NULL,
 
  OLD_TITLE varchar(255) DEFAULT NULL,
  NEW_TITLE varchar(255) DEFAULT NULL,
  
  OLD_PUBYEAR int(4) DEFAULT NULL,
  NEW_PUBYEAR int(4) DEFAULT NULL,
  
  OLD_BESTSELLER tinyint(1) DEFAULT NULL,
  NEW_BESTSELLER tinyint(1) DEFAULT NULL,
  
  PRIMARY KEY (EVENT_ID)
  );