CREATE TABLE READERS_AUD (
  EVENT_ID int(11) NOT NULL AUTO_INCREMENT,
  EVENT_DATE datetime NOT NULL,
  EVENT_TYPE varchar(10) DEFAULT NULL,
  READER_ID int(11) NOT NULL,
 
  OLD_FIRSTNAME varchar(255) DEFAULT NULL,
  NEW_FIRSTNAME varchar(255) DEFAULT NULL,
  
  OLD_LASTNAME varchar(255) DEFAULT NULL,
  NEW_LASTNAME varchar(255) DEFAULT NULL,
  
  OLD_PESELID varchar(11) DEFAULT NULL,
  NEW_PESELID varchar(11) DEFAULT NULL,
  
  OLD_VIP_LEVEL varchar(20) DEFAULT NULL,
  NEW_VIP_LEVEL varchar(20) DEFAULT NULL,
  
  PRIMARY KEY (EVENT_ID)
  );